distance_eqtl_ALL: 'D:/Hanze_Groningen/STAGE/eQTL/distance_eqtl_ALL.tsv'
eQTL_zero_distance: 'D:/Hanze_Groningen/STAGE/R/eQTL_zero_distance.tsv'
database: 'D:/Hanze_Groningen/STAGE/db_laatste_copy.db'
GT_file: 'D:/Hanze_Groningen/STAGE/R/GT.tsv'
GT_file_breast: 'D:/Hanze_Groningen/STAGE/R/GT_breast.tsv'
GT_file_nonbreast: 'D:/Hanze_Groningen/STAGE/R/GT_nonbreast.tsv'
GT_file_both: 'D:/Hanze_Groningen/STAGE/R/GT_count_ALL.tsv'
output_hj: 'C:/Users/Anne_/Downloads/output_1.txt'
save_output: 'C:/Users/Anne_/Downloads/output'
COSMIC_CGC: 'C:/Users/Anne_/Downloads/cosmic_genes.csv'
directory: 'E:/analyse/new/correction/genes/bon/all/'
path_new_file: 'E:/analyse/new/correction/genes/bon/all_list2/'
path_snps_filtering: 'D:/Hanze_Groningen/STAGE/snps_after_filtering_unique.tsv'
all_SNPs: 'E:/analyse/new/correction/snps/all/per_snp_ALL_ALL_sig_snps_NEW.tsv'
directory_snp: 'E:/analyse/new/correction/snps/all/'
path_new_file_snp: 'E:/analyse/new/correction/snps/all_list2/'
GT2: 'D:/Hanze_Groningen/STAGE/GT2.tsv'
allgenes: 'D:/Hanze_Groningen/STAGE/allgenes.tsv.gz'
Region_2000: 'D:/Hanze_Groningen/STAGE/Region_2000_ALL_both_0_TESTS.tsv.gz'
output_overlap: 'D:/Hanze_Groningen/STAGE/output.tsv'


