all_vcf: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/all_vcf.tsv.gz' 
allfiles: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/allfiles.tsv.gz'
ALL_WGS_tot_mut: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/data_db/000000ALL_WGS_tot_mut.tsv.gz'
all_sig_eqtl: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/2019-12-11-cis-eQTLsFDR0.05-ProbeLevel-CohortInfoRemoved-BonferroniAdded.txt'
all_genes: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/all_genes_new.tsv'
all_specimen: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/self_made/all_specimen.tsv'
allel_freq: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/vcf/allel_freq/'
analyse: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/analyse/'
analyse_new: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/analyse/new/'

cancer_data_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/'
checkGene: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/snp132_ucsc_hg19_checkGene.bed'
chromosome_fa: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/chr/unzip/'
database: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_laatste_copy.db'
database_2: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_laatste_copy2.db'
database_scripts: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/non-coding-somatic-mutations-in-cancer/Anne/scripts/database2/'
database_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_data_db/'
database_TFBS: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_TFBS.db'
database_DNase: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_DNase.db'
database_UCNE: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_UCNE.db'
database_get_data: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/db_get_data.db'
distance_eqtl_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/distance_eqtl.tsv'
DNase: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/GREEN_DB/2022-04-13_GRCh37_DNase.merged.bed.gz'
donor_info: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/self_made/donor.tsv'
genes_eQTL_etc: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/'
genoom_fa: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/chr/chrall.dict'
germline_resource: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/GermlineResource/merge_af-only-gnomad.raw.sites.vcf'
layers: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/layers/'
new_plan2: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/non-coding-somatic-mutations-in-cancer/Anne/scripts/new_plan2/'
Number_and_none_values: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/Number_and_none_values.txt'
panel_of_normals: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/PanelOfNormals/merge_somatic-b37_Mutect2-WGS-panel-b37.vcf'
path_genoom: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/chr/'
pipeline_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/non-coding-somatic-mutations-in-cancer/Anne/scripts/pipeline/'
pipeline_jobs: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/non-coding-somatic-mutations-in-cancer/Anne/scripts/pipeline/jobs/'
path_R: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/analyse/R/'
sample_file: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/datasets/EGAD00001000292/EGAD00001000292_metadata/delimited_maps/Sample_File.map'
sample_folder: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/datasets/EGAD00001000292/samples/'
save_extra_layers: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/{name_variant}_num_snps.tsv'
script_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/non-coding-somatic-mutations-in-cancer/Anne/scripts/'
site: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/self_made/site.csv'
strong_eqtl_noInfo: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/eQTL/eqtl_v1013_lead_snp_gene.txt'
strong_eqtl_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/genes_eQTL_etc/eqtl_v1013_lead_snp_gene_with_info.txt'
test_database: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/new_db/test.db'
TFBS: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/GREEN_DB/2022-04-13_GRCh37_TFBS.merged.bed.gz'
UCNE: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/GREEN_DB/2022-04-13_GRCh37_UCNE.bed.gz'
umap_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/UMAP/'
vcf_path: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/vcf/'
vcf_all: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/vcf/ALL.vcf.gz'
vcf_allel_freq: '/groups/umcg-wijmenga/tmp04/projects/lude_vici_2021/rawdata/cancer_data/vcf/vcf_allel_freq/'

# database: "D:/Hanze_Groningen/STAGE/db_laatste_copy.db"
# all_genes: "D:/Hanze_Groningen/STAGE/db/all_genes_new.tsv"
# umap_path: "D:/Hanze_Groningen/STAGE/UMAP/"